#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/7bd5c07998f74949973af246a933c7c0654cd0c097942cd58e4889c57ec9f67e/contract';
import endContract from '../../snapshots/7bd5c07998f74949973af246a933c7c0654cd0c097942cd58e4889c57ec9f67e/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'accounts',
        columns: [
          col('access_token', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expires_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('password', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('profile_raw', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('provider_account_id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('refresh_token', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('scope', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('token_type', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'accounts_type_check_2f22e716',
            "\"type\" IN ('LOCAL', 'GOOGLE', 'APPLE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'audit_logs',
        columns: [
          col('changes', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('controller', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('duration_ms', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('error_message', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('handler', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('ip_address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('method', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('request_body', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('request_headers', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('request_id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('request_params', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('request_query', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('response_body', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('role_code', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('route', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status_code', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('user_agent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('user_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'documents',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deleted_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('extract_quality', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('extracted_key', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('failure_reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('media_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('page_count', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('rewrite_mode', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('source_hash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('QUEUED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('storage_prefix', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('total_chars', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('total_duration_ms', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'documents_extract_quality_check_34bdf103',
            "\"extract_quality\" IN ('OK', 'LOW')",
          ),
          checkExpression(
            'documents_rewrite_mode_check_74da5c5e',
            "\"rewrite_mode\" IN ('RAW', 'FLUENT')",
          ),
          checkExpression(
            'documents_status_check_30cbb25c',
            "\"status\" IN ('QUEUED', 'EXTRACTING', 'SCRIPTING', 'SYNTHESIZING', 'READY', 'PARTIAL', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'job_executions',
        columns: [
          col('affected_rows', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('duration', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('end_time', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('error_message', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('job_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('metadata', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('retry_count', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('start_time', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'job_executions_status_check_65f4a11e',
            "\"status\" IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'jobs',
        columns: [
          col('category', 'text', {
            notNull: true,
            default: lit('MAINTENANCE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('code', 'character varying(100)', {
            notNull: true,
            codecRef: { codecId: 'sql/varchar@1', typeParams: { length: 100 } },
          }),
          col('consecutive_failures', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('cron_pattern', 'character varying(50)', {
            notNull: true,
            codecRef: { codecId: 'sql/varchar@1', typeParams: { length: 50 } },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('last_execution_at', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('last_failure_at', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('last_success_at', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('name', 'character varying(200)', {
            notNull: true,
            codecRef: { codecId: 'sql/varchar@1', typeParams: { length: 200 } },
          }),
          col('params', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('retry_limit', 'int4', {
            notNull: true,
            default: lit(3),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'jobs_category_check_8228a3ae',
            "\"category\" IN ('MAINTENANCE', 'NOTIFICATION', 'DATA_SYNC', 'CLEANUP', 'OTHER')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'llm_usage',
        columns: [
          col('cache_read_tokens', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('cache_write_tokens', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('cost_usd', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('document_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('input_tokens', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('model', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('output_tokens', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('section_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'media',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('duration', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('file_name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('height', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('metadata', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('mime_type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('size', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('storage_key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('uploader_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('width', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'notification_templates',
        columns: [
          col('channel', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('content', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('params', 'text[]', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1', many: true },
          }),
          col('subject', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('template', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'notification_templates_channel_check_96614c37',
            "\"channel\" IN ('EMAIL', 'SMS', 'PUSH')",
          ),
          checkExpression(
            'notification_templates_params_elem_not_null_88a787ca',
            'array_position("params", NULL) IS NULL',
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'notifications',
        columns: [
          col('actions', 'jsonb', {
            notNull: true,
            default: lit([]),
            codecRef: { codecId: 'pg/jsonb@1' },
          }),
          col('actor_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('entity_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('entity_type', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('is_read', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('message', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('read_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('recipient_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('title', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'notifications_entity_type_check_7aa73585',
            '"entity_type" IN (\'Document\')',
          ),
          checkExpression(
            'notifications_type_check_db261f90',
            "\"type\" IN ('PASSWORD_CHANGED', 'ACCOUNT_LOCKED', 'NEW_DEVICE_LOGIN', 'DOCUMENT_READY', 'DOCUMENT_FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'permissions',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deleted_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('module', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'playback_progress',
        columns: [
          col('completed', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('position_ms', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('section_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'push_tokens',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('platform', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('token', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'push_tokens_platform_check_120bc35e',
            "\"platform\" IN ('IOS', 'ANDROID')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'revenuecat_events',
        columns: [
          col('app_user_id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('event_id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('payload', 'jsonb', { notNull: true, codecRef: { codecId: 'pg/jsonb@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'role_permissions',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('permission_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('role_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'roles',
        columns: [
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deleted_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('is_super', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('is_system', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rank', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sections',
        columns: [
          col('attempts', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('audio_key', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('char_count', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('document_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('duration_ms', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('failure_reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('model', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('order', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('page_end', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('page_start', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('prompt_version', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('script', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('script_hash', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('size_bytes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('source_text', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'sections_status_check_43b86a93',
            "\"status\" IN ('PENDING', 'SCRIPTING', 'SCRIPTED', 'SYNTHESIZING', 'READY', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'subscriptions',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('current_period_end', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('last_event_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('plan', 'text', {
            notNull: true,
            default: lit('FREE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('product_id', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('rc_app_user_id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('store', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('subscriptions_plan_check_11a46379', "\"plan\" IN ('FREE', 'PRO')"),
          checkExpression(
            'subscriptions_status_check_0c2daa37',
            "\"status\" IN ('ACTIVE', 'GRACE', 'EXPIRED', 'CANCELLED')",
          ),
          checkExpression(
            'subscriptions_store_check_7b73277d',
            "\"store\" IN ('APP_STORE', 'PLAY_STORE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'usage_ledger',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('document_id', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('pages', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('period_key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user_consents',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('granted', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('ip_address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('user_agent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('version', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'user_consents_type_check_2eb1bc97',
            "\"type\" IN ('PRIVACY_NOTICE', 'TERMS_OF_USE', 'CROSS_BORDER_TRANSFER')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'users',
        columns: [
          col('bio', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deleted_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('is_email_verified', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('last_login_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('last_login_method', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('surname', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('username', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'users_last_login_method_check_379e5f3a',
            "\"last_login_method\" IN ('LOCAL', 'GOOGLE', 'APPLE')",
          ),
          checkExpression(
            'users_status_check_7c5ddd00',
            "\"status\" IN ('PENDING', 'ACTIVE', 'SUSPENDED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'verification_tokens',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expires_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('token', 'character(48)', {
            notNull: true,
            codecRef: { codecId: 'sql/char@1', typeParams: { length: 48 } },
          }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('user_id', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'verification_tokens_type_check_5a4470d6',
            "\"type\" IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')",
          ),
        ],
      }),
      this.addUnique({
        schema: 'public',
        table: 'accounts',
        constraint: 'accounts_type_provider_account_id_key',
        columns: ['type', 'provider_account_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'jobs',
        constraint: 'jobs_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'notification_templates',
        constraint: 'notification_templates_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'notification_templates',
        constraint: 'notification_templates_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'notifications',
        constraint: 'notifications_target_key',
        columns: ['recipient_id', 'actor_id', 'type', 'entity_type', 'entity_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'permissions',
        constraint: 'permissions_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'permissions',
        constraint: 'permissions_module_action_key',
        columns: ['module', 'action'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'playback_progress',
        constraint: 'playback_progress_user_id_section_id_key',
        columns: ['user_id', 'section_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'push_tokens',
        constraint: 'push_tokens_token_key',
        columns: ['token'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'revenuecat_events',
        constraint: 'revenuecat_events_event_id_key',
        columns: ['event_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'role_permissions',
        constraint: 'role_permissions_role_id_permission_id_key',
        columns: ['role_id', 'permission_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'roles',
        constraint: 'roles_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'roles',
        constraint: 'roles_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'sections',
        constraint: 'sections_document_id_order_key',
        columns: ['document_id', 'order'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'subscriptions',
        constraint: 'subscriptions_user_id_key',
        columns: ['user_id'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'users',
        constraint: 'users_username_key',
        columns: ['username'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'users',
        constraint: 'users_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'verification_tokens',
        constraint: 'verification_tokens_token_key',
        columns: ['token'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'verification_tokens',
        constraint: 'verification_tokens_user_id_type_key',
        columns: ['user_id', 'type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'accounts',
        index: 'accounts_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_created_at_idx_225d8c0f',
        columns: ['created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_request_id_idx_0aa129e0',
        columns: ['request_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_route_method_idx_b89d147a',
        columns: ['route', 'method'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_status_code_idx_0b2ed12c',
        columns: ['status_code'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_user_id_created_at_idx_b562028f',
        columns: ['user_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'documents',
        index: 'documents_media_id_idx_495ca900',
        columns: ['media_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'documents',
        index: 'documents_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'documents',
        index: 'documents_user_id_created_at_idx_b562028f',
        columns: ['user_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'documents',
        index: 'documents_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'documents',
        index: 'documents_user_id_source_hash_idx_032002fb',
        columns: ['user_id', 'source_hash'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'job_executions',
        index: 'job_executions_job_id_created_at_idx_98a4c64c',
        columns: ['job_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'job_executions',
        index: 'job_executions_job_id_idx_58a5bbdd',
        columns: ['job_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'job_executions',
        index: 'job_executions_job_id_status_start_time_idx_a5fd7b77',
        columns: ['job_id', 'status', 'start_time'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'job_executions',
        index: 'job_executions_status_start_time_idx_3059bedc',
        columns: ['status', 'start_time'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'jobs',
        index: 'jobs_category_is_active_idx_1d997382',
        columns: ['category', 'is_active'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'jobs',
        index: 'jobs_code_idx_8e43b86b',
        columns: ['code'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'jobs',
        index: 'jobs_is_active_idx_68cfa343',
        columns: ['is_active'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'jobs',
        index: 'jobs_last_execution_at_idx_73dc5057',
        columns: ['last_execution_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'llm_usage',
        index: 'llm_usage_created_at_idx_225d8c0f',
        columns: ['created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'llm_usage',
        index: 'llm_usage_document_id_idx_d3d0944e',
        columns: ['document_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'llm_usage',
        index: 'llm_usage_section_id_idx_13db6de7',
        columns: ['section_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'media',
        index: 'media_uploader_id_idx_7e6af2c2',
        columns: ['uploader_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notification_templates',
        index: 'notification_templates_channel_idx_6b06af25',
        columns: ['channel'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notifications',
        index: 'notifications_actor_id_idx_69a2164d',
        columns: ['actor_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notifications',
        index: 'notifications_recipient_id_created_at_idx_fb9c4b0b',
        columns: ['recipient_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notifications',
        index: 'notifications_recipient_id_idx_1e4ca6fd',
        columns: ['recipient_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notifications',
        index: 'notifications_recipient_id_is_read_created_at_idx_681b2a09',
        columns: ['recipient_id', 'is_read', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'playback_progress',
        index: 'playback_progress_section_id_idx_13db6de7',
        columns: ['section_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'playback_progress',
        index: 'playback_progress_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'playback_progress',
        index: 'playback_progress_user_id_updated_at_idx_f41263b4',
        columns: ['user_id', 'updated_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'push_tokens',
        index: 'push_tokens_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'revenuecat_events',
        index: 'revenuecat_events_app_user_id_idx_9295d5b4',
        columns: ['app_user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'role_permissions',
        index: 'role_permissions_permission_id_idx_909cec36',
        columns: ['permission_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'role_permissions',
        index: 'role_permissions_role_id_idx_d9467c50',
        columns: ['role_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sections',
        index: 'sections_document_id_idx_d3d0944e',
        columns: ['document_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sections',
        index: 'sections_document_id_status_idx_26c220cf',
        columns: ['document_id', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'usage_ledger',
        index: 'usage_ledger_document_id_idx_d3d0944e',
        columns: ['document_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'usage_ledger',
        index: 'usage_ledger_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'usage_ledger',
        index: 'usage_ledger_user_id_period_key_idx_52f386cc',
        columns: ['user_id', 'period_key'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'user_consents',
        index: 'user_consents_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'user_consents',
        index: 'user_consents_user_id_type_created_at_idx_d651f8e0',
        columns: ['user_id', 'type', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_email_idx_46df9cad',
        columns: ['email'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_name_idx_ce87e6ba',
        columns: ['name'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_role_id_idx_d9467c50',
        columns: ['role_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_surname_idx_f13ed75d',
        columns: ['surname'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_username_idx_b719d535',
        columns: ['username'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'verification_tokens',
        index: 'verification_tokens_token_idx_8b25281e',
        columns: ['token'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'verification_tokens',
        index: 'verification_tokens_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'accounts',
        foreignKey: {
          name: 'accounts_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'documents',
        foreignKey: {
          name: 'documents_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'documents',
        foreignKey: {
          name: 'documents_media_id_fkey',
          columns: ['media_id'],
          references: { schema: 'public', table: 'media', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'job_executions',
        foreignKey: {
          name: 'job_executions_job_id_fkey',
          columns: ['job_id'],
          references: { schema: 'public', table: 'jobs', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'llm_usage',
        foreignKey: {
          name: 'llm_usage_document_id_fkey',
          columns: ['document_id'],
          references: { schema: 'public', table: 'documents', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'llm_usage',
        foreignKey: {
          name: 'llm_usage_section_id_fkey',
          columns: ['section_id'],
          references: { schema: 'public', table: 'sections', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'notifications',
        foreignKey: {
          name: 'notifications_recipient_id_fkey',
          columns: ['recipient_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'notifications',
        foreignKey: {
          name: 'notifications_actor_id_fkey',
          columns: ['actor_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'playback_progress',
        foreignKey: {
          name: 'playback_progress_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'playback_progress',
        foreignKey: {
          name: 'playback_progress_section_id_fkey',
          columns: ['section_id'],
          references: { schema: 'public', table: 'sections', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'push_tokens',
        foreignKey: {
          name: 'push_tokens_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'role_permissions',
        foreignKey: {
          name: 'role_permissions_role_id_fkey',
          columns: ['role_id'],
          references: { schema: 'public', table: 'roles', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'role_permissions',
        foreignKey: {
          name: 'role_permissions_permission_id_fkey',
          columns: ['permission_id'],
          references: { schema: 'public', table: 'permissions', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sections',
        foreignKey: {
          name: 'sections_document_id_fkey',
          columns: ['document_id'],
          references: { schema: 'public', table: 'documents', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'subscriptions',
        foreignKey: {
          name: 'subscriptions_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'usage_ledger',
        foreignKey: {
          name: 'usage_ledger_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'usage_ledger',
        foreignKey: {
          name: 'usage_ledger_document_id_fkey',
          columns: ['document_id'],
          references: { schema: 'public', table: 'documents', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'user_consents',
        foreignKey: {
          name: 'user_consents_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'users',
        foreignKey: {
          name: 'users_role_id_fkey',
          columns: ['role_id'],
          references: { schema: 'public', table: 'roles', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'verification_tokens',
        foreignKey: {
          name: 'verification_tokens_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
